# fly.toml app configuration file generated for consultar-estoque on 2024-10-08T17:08:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'consultar-estoque'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
